### ISSUE TITLE
how to 

### ISSUE THREAD

**Issue by gadgetreviews** [flame-engine/flame_splash_screen#6]
Hello,

In fact, this is not an issue or problem report. I just want to ask a how to question. 

I want to make a Loading Screen for a game that I am developing. I want to show just my game's logo and remove flame logo. Is it possible to this with this package?

Also, if it is possible I want to show a percentage bar and update it while loading assets. And loading screen will be dismissed as soon as last asset loaded.

**Comment by renancaraujo** [comment]
Everything is possible if you fork it.

The very goal of the package is to show support for the free and open source flame engine.

Anyway, it is possible to show your logo before or after flames logo. Also, after the last step of the splash screen animation, you can execute a callback that pretty much can do anything, even going to a route where you can show your progress bar.
