### ISSUE TITLE
Null error occurred

### ISSUE THREAD

**Issue by hmlyn523** [flame-engine/flame_splash_screen#9]
Maybe I'm using it wrong, but I sometimes get the following error This does not always happen.

[VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: Null check operator used on a null value
#0      AnimationController.stop (package:flutter/src/animation/animation_controller.dart:777)
#1      AnimationController.value= (package:flutter/src/animation/animation_controller.dart:364)
#2      __SplashScreenStepState.startAnimation (package:flame_splash_screen/src/splash.dart:162)
<asynchronous suspension>

**Comment by erickzanardo** [comment]
Can you provide a minimal reproducible code?

**Comment by hmlyn523** [comment]
Yes, sir.I will include it here when it is ready.

**Comment by spydon** [comment]
This is fixed (not yet released though), and the code has been moved  here:
https://github.com/flame-engine/flame/tree/main/packages/flame_splash_screen

**Comment by spydon** [comment]
Released the fix in 0.2.0
